version: "3"
services:
  temo_redis:
    container_name: temo_redis
    image: "redis:alpine"
    ports:
      - "$REDIS_PORT:6379"
  temo_db:
    container_name: temo_db
    image: postgres:latest
    restart: always
    ports:
    - $POSTGRES_PORT:5432
    volumes:
    - ./data/postgres:/data/postgres
    env_file:
    - .env

  # temo_mailhog:
  #   container_name: temo_mailhog
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'  # disable saving logs
  #   ports:
  #     - $MAIL_PORT:1025
  #     - $MAIL_UI_PORT:8025
 
  temo_adminer:
    links:
    - $POSTGRES_DB:postgres
    container_name: temo_adminer
    restart: always
    image: adminer
    ports:
    - $ADMINER_PORT:8080